### ISSUE TITLE
Indicate upload status for file upload

### ISSUE THREAD

**Issue by yogeshVU** [webgme/webgme-taxonomy#121]
Currently there is no indicator of  how much has been uploaded or ETA of the file upload.

**Comment by romancow** [comment]
@yogeshVU @brollb How do you think this should work UI/UX wise? Or at least for the initial version? Should the status just show in the actual dialog window and make it so it can't be dismissed until it is completed? This is probably the easiest approach, yet the least user friendly.

Another idea is something like a svelte ui  ["snackbar" component](https://sveltematerialui.com/demo/snackbar/) that pops up at the bottom showing the upload status after the dialog closes. I don't this is bad, but it looks like you can only have one open at a time. Are we going to allow multiple uploads at once? I guess the "Toast" component we are already using for errors might be a good alternative if we allow multiple uploads, since it can show multiple such messages at a time. I'm not sure what all options it has in terms of keeping it on, updating it's progress bar, etc.

A third potential option is to add something like an "uploads" dropdown button to the top app bar. So I'm thinking when there is something uploading, the button would appear. You could then click it to get a little drop-down list of current status of uploads. This would allow multiple uploads, and not clutter up the screen with a bunch of statuses when you don't want to see them.

Let me know your guys thoughts.

**Comment by yogeshVU** [comment]
From the dialog box, we can support multiple file uploads. So given the time constraints I think it would be good to get a release with the easiest alternative to begin with and then iterate/refine the feature as we get more feedback.

**Comment by romancow** [comment]
True, but the dialog only allows multiple files to a single artifact set. And they will be blocked UX-wise from doing anything else while it uploads.

**Comment by yogeshVU** [comment]
I think that constraint of allowing just a single upload session will work for this, unless there is really a request to support concurrent upload sessions.
