### ISSUE TITLE
Autocomplete text fields in "Advanced Filters" based on current items

### ISSUE THREAD

**Issue by brollb** [webgme/webgme-taxonomy#17]
Text properties in the advanced filters (on the Data Dashboard) should be autocompleted based on the current items (given the current partial filter).

**Comment by brollb** [comment]
Relevant link: https://sveltematerialui.com/demo/autocomplete/

**Comment by brollb** [comment]
It would be nice to use fuzzy search for determining the autocompletion values.

**Comment by romancow** [comment]
@brollb -- I added the autocomplete field, but on testing discovered that I don't think it behaves quite how we'd want. Basically the issue is, it doesn't appear to be reactive on its `options` prop. Meaning, if the autocomplete's `options` changes, the suggestions it shows doesn't change (until you actually change the value in the text box).

So what this results in, UX-wise, is you can be selecting/deselecting a bunch of advanced filters, then you select an autocomplete field and the autocomplete suggestions pop up. But what pops up is what was set before you do all your other advanced filtering. So the suggestions don't actually match the current results on the right side. Then once you type (or delete a character), the suggestions refresh to something different.

You can see the logic for this in the smui autocomplete source: https://github.com/hperrin/svelte-material-ui/blob/master/packages/autocomplete/src/Autocomplete.svelte#L178

The logic where it updates what to show (line 189: `matches = searchResult;`) is wrapped in this conditional:

```javascript
$: if (previousText !== text) {
```
So as long as the field's text doesn't change, it's not gonna update its suggestions.

I think there are a few options here. We could just go with this behavior, but it doesn't really feel right at all. Another option is to update the autocomplete's source ourselves. I think I managed to hack something that worked by exporting a function from the autocomplete component that could be called to manually update it, and then calling this when options changed.

Regardless of what we want to do, I can file an issue with smui with a request to support this behavior.

Let me know your thoughts.

**Comment by romancow** [comment]
Also, I was going to push my branch so you could take a look, but it doesn't appear I have permission to.

**Comment by romancow** [comment]
One more thing... it appears that the autocomplete does have a `search` prop where you can pass a function to customize its suggestions. I haven't tried it yet, but I believe this could be used to support fuzzy match. I wanted to figure out what to do about the option updating first before delving into that, though.

**Comment by romancow** [comment]
Adding reference to issue opened for svelte-material-ui:
hperrin/svelte-material-ui#519

**Comment by romancow** [comment]
@brollb - No response yet on the smui issue I opened. I added a new branch with a solution that patches the Autocomplete component to refresh when options are changed. Take a look [here](https://github.com/webgme/webgme-taxonomy/compare/17-autocomplete-advanced-filters-patch), and let me know if I should go ahead and create a pull request for it.
